export const recipes = [
  {
    id: "r1",
    categories: ["한식"],
    title: "감자조림",
    imageUrl: "",
    ingredients: ["감자", "간장", "설탕", "식용유"],
    steps: [
      "감자를 깨끗이 씻어주세요.",
      "감자를 먹기 좋은 크기로 잘라주세요.",
      "냄비에 감자와 간장, 설탕, 식용유를 넣고 조립니다.",
      "10분 정도 조린 후 완성됩니다.",
    ],
    duration: 15,
    complexity: "초급",
    affordability: "저렴",
  },
  {
    id: "r2",
    categories: ["한식"],
    title: "닭갈비",
    imageUrl: "",
    ingredients: ["닭고기", "고추장", "고춧가루", "양파"],
    steps: [
      "닭고기를 적당한 크기로 잘라주세요.",
      "양파를 채 썰어주세요.",
      "냄비에 닭고기와 양파, 고추장, 고춧가루를 넣고 볶아주세요.",
      "20분 정도 볶은 후 완성됩니다.",
    ],
    duration: 30,
    complexity: "중급",
    affordability: "보통",
  },
  {
    id: "r3",
    categories: ["한식"],
    title: "콩나물국",
    imageUrl: "",
    ingredients: ["콩나물", "소고기", "대파"],
    steps: [
      "소고기와 대파를 끓여 육수를 내주세요.",
      "콩나물을 넣고 끓여주세요.",
      "10분 정도 끓인 후 완성됩니다.",
    ],
    duration: 25,
    complexity: "초급",
    affordability: "저렴",
  },
  {
    id: "r4",
    categories: ["한식"],
    title: "불고기",
    imageUrl: "",
    ingredients: ["소고기", "양파", "마늘", "간장", "설탕", "참기름"],
    steps: [
      "소고기는 얇게 썰어주세요.",
      "양파와 마늘은 적당히 썰어주세요.",
      "볼에 간장, 설탕, 참기름을 섞어주세요.",
      "소고기, 양파, 마늘을 볼에 넣고 손으로 조물조물 섞어주세요.",
      "팬에 볶아주세요.",
      "완성!",
    ],
    duration: 30,
    complexity: "초급",
    affordability: "저렴",
  },
  {
    id: "r5",
    categories: ["한식"],
    title: "된장찌개",
    imageUrl: "",
    ingredients: [
      "된장",
      "두부",
      "양파",
      "청양고추",
      "파",
      "마늘",
      "물",
      "소금",
      "식용유",
    ],
    steps: [
      "두부와 양파는 적당한 크기로 자릅니다.",
      "청양고추와 파는 어슷하게 썰어줍니다.",
      "냄비에 물을 붓고, 두부와 양파를 넣어 끓입니다.",
      "마늘을 볶다가 된장을 넣어 섞어주세요.",
      "볶은 마늘과 된장을 냄비에 넣어주고 10분간 끓입니다.",
      "10분 후 청양고추와 파를 넣고 간을 맞춰주세요.",
      "완성!",
    ],
    duration: 40,
    complexity: "초급",
    affordability: "저렴",
  },
  {
    id: "r6",
    categories: ["한식"],
    title: "김치찌개",
    imageUrl: "",
    ingredients: ["김치", "돼지고기", "두부"],
    steps: ["김치와 돼지고기를 냄비에 넣고 끓인다.", "두부를 넣고 더 끓인다."],
    duration: 30,
    complexity: "쉬움",
    affordability: "저렴함",
  },
  {
    id: "r7",
    categories: ["일식"],
    title: "돈부리",
    imageUrl: "",
    ingredients: ["돼지고기", "양파", "계란"],
    steps: ["돼지고기와 양파를 볶는다.", "계란을 올린다."],
    duration: 20,
    complexity: "보통",
    affordability: "보통",
  },
  {
    id: "r8",
    categories: ["양식"],
    title: "스테이크",
    imageUrl: "",
    ingredients: ["소고기", "감자", "양파"],
    steps: ["스테이크를 구워서 그릴 마크를 낸다.", "감자와 양파를 볶는다."],
    duration: 45,
    complexity: "어려움",
    affordability: "고가",
  },
  {
    id: "r9",
    categories: ["중식"],
    title: "짜장면",
    imageUrl: "",
    ingredients: ["면", "고추장", "돼지고기"],
    steps: [
      "면을 끓인다.",
      "고추장과 돼지고기를 볶는다.",
      "면에 고추장을 얹고 돼지고기를 올린다.",
    ],
    duration: 30,
    complexity: "보통",
    affordability: "보통",
  },
];
